{% set name = "psij-python" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/psij-python-{{ version }}.tar.gz
  sha256: 79d527e43a5bb0df00818b956cc4dec064b59c38e4f8557e8533f901cb47d68f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - filelock >=3.4,<4.dev0
    - packaging >=24.0,<=24.2
    - psutil >=5.9,<=6.1.1
    - pystache >=0.6.0
    - typeguard >=3.0.1
    - typing-compat

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/exaworks/psij-python
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs) specification.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/exaworks/psij-python
  doc_url: https://exaworks.org/psij-python/#docs

extra:
  recipe-maintainers:
    - xylar
    - jan-janssen
